version: 2.1
orbs:
  slack: circleci/slack@4.8.3
jobs:
  get_all_known_ips:
    resource_class: small
    docker:
      - image: buildpack-deps:impish-scm
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ROLE_ARN: $AWS_ROLE_ARN
    steps:
      - checkout
      - run: |
          apt update && apt install -y dnsutils
      # overwrites (truncates) the earlier all.knownips.circleci.com.txt
      - run: |
          dig all.knownips.circleci.com A +short | sort > all.knownips.circleci.com.txt
      - run: |
          cat all.knownips.circleci.com.txt
      # git diff returns non-zero exit if there has been a difference
      - run: |
          git diff all.knownips.circleci.com.txt
      - run: 
         name: authenticate-and-interact 
         command: |
           apt update -y
           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
           apt install unzip -y
           unzip awscliv2.zip
           ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
           aws --version
           # use the OpenID Connect token to obtain AWS credentials
           read AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \<<< \
              $(aws sts assume-role-with-web-identity \
              --role-arn ${AWS_ROLE_ARN} \
              --role-session-name "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}" \
              --web-identity-token $CIRCLE_OIDC_TOKEN \
              --duration-seconds 3600 \
              --region us-east-1 \
              --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
              --output text)
           export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
           # interact with AWS
           aws sts get-caller-identity
          
workflows:
  inspect_changes:
    jobs:
      - get_all_known_ips:
          context: 
            - my-context